name: my_First_CI_CD
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code CheckOut
        uses: actions/checkout@v4

      - name: jdk setup
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"

      -  name: grant execute permition to gradle
         run: chmod +x gradlew

      - name: run Lint
        run: ./gradlew lintDebug

      - name: run test case
        run: ./gradlew test

      - name:   build apk
        run: ./gradlew assembleDebug

      - name: upload apk to actifire
        uses: actions/upload-artifact@v4
        with:
          name: Android build
          path:  app/build/outputs/apk/debug/*.apk



